spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
       ddl-auto: update
       jdbc:
         lob:
           non_contextual_creation: true
         database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  thymeleaf:
    enabled: true
    encoding: UTF-8
    cache: false
    check-template: true
    check-template-location: true
    mode: HTML
    template-resolver-order: 0



server:
  port: 8081